### PR TITLE
Support pagination for fetching users and rooms

### PR DESCRIPTION
**Pull request by artfuldodger**
Enable pagination, without which it is impossible to get more than 100 rooms or users.

### CODE REVIEW

**Comment by rberrelleza** [comment]
Thanks! Could you add a unit test for the room pagination use case?

**Comment by artfuldodger** [comment]
@rbergman Sure thing! Added a new commit with some specs.

**Comment by artfuldodger** [comment]
@rbergman Need anything from me here to help get this merged?

**Comment by rberrelleza** [comment]
Thanks for your contribution!

**Pull request merged**
