### PR TITLE
add notify as an option to direct messages

### PR DESCRIPTION
**Pull request by flyinbutrs**
Fixes #168

### CODE REVIEW

**Comment by rberrelleza** [comment]
Thanks for the contribution! Your change is breaking CI though, could you fix those so I can merge it? (awthanks)

**Comment by flyinbutrs** [comment]
Fixed, updated test

**Comment by rberrelleza** [comment]
Thanks!

**Comment by flyinbutrs** [comment]
So when is the next release? Or are these changes continually added to rubygems.org?

**Comment by rberrelleza** [comment]
I pushed the new version of the gem with your changes this morning.

**Pull request merged**
